'use client';
import React,{useState}from'react';
import{Camera,ShieldAlert,Pill,RefreshCw,Crown,Database,User,Activity}from'lucide-react';
import'./style.css';
const rules=[['red 40','Synthetic dye often avoided by sensitive users','high'],['maltodextrin','Hidden fast carbohydrate with sugar-like impact','medium'],['natural flavors','Opaque ingredient term; may hide compounds','medium'],['sodium nitrite','Processed meat preservative concern','high'],['ibuprofen','NSAID: check stomach, kidney, blood pressure risks','medium'],['warfarin','Blood thinner; interaction risk with NSAIDs','high'],['paraben','Cosmetic preservative many users avoid','medium'],['fragrance','Opaque allergen risk in cosmetics','medium'],['yohimbine','High-risk stimulant supplement','high'],['proprietary blend','Hides exact doses; transparency problem','medium'],['oats','Positive whole-grain fiber signal','good'],['glycerin','Good skin hydration ingredient','good']];
const samples={food:'maltodextrin, red 40, natural flavors, sodium nitrite, oats',medicine:'ibuprofen 400mg. Do not use with warfarin or aspirin. May cause stomach bleeding.',cosmetic:'water, fragrance, paraben, glycerin',supplement:'caffeine, yohimbine, proprietary blend'};
export default function App(){const[type,setType]=useState('food'),[text,setText]=useState(samples.food),[allergy,setAllergy]=useState(''),[meds,setMeds]=useState('warfarin'),[report,setReport]=useState(null);function analyze(){let f=[];let t=text.toLowerCase();rules.forEach(r=>{if(t.includes(r[0]))f.push({name:r[0],desc:r[1],risk:r[2]})});if(t.includes('ibuprofen')&&meds.toLowerCase().includes('warfarin'))f.unshift({name:'ibuprofen + warfarin',desc:'Potential serious bleeding interaction. Ask a pharmacist or doctor.',risk:'high'});if(allergy&&t.includes(allergy.toLowerCase()))f.unshift({name:allergy,desc:'Personal allergy match detected.',risk:'high'});let high=f.filter(x=>x.risk==='high').length,med=f.filter(x=>x.risk==='medium').length,good=f.filter(x=>x.risk==='good').length;let score=Math.max(5,Math.min(98,88-high*18-med*8+good*5));setReport({score,f,high,med,good});}
return <main><nav><b className="logo">◎ TruthLabel</b><span>Independent product intelligence</span></nav><section className="hero"><div><p className="tag">No ads. No brand deals. User-first truth.</p><h1>Decode anything that goes into your body.</h1><p className="lead">Food, medicine, supplements and cosmetics with personal alerts, interaction checks, safer alternatives, history and premium subscription flow.</p><button onClick={analyze}>Run Truth Scan</button></div><div className="phone"><Camera size={56}/><h3>AI label scanner</h3><p>Camera/OCR/Vision-ready interface</p></div></section><section className="grid"><Card icon={<ShieldAlert/>} title="Harm detection" text="Additives, dyes, preservatives, irritants and risky stimulants."/><Card icon={<Pill/>} title="Medicine interactions" text="NSAIDs, blood thinners, aspirin and condition warnings."/><Card icon={<RefreshCw/>} title="Alternatives" text="Cleaner options by category, price and risk profile."/><Card icon={<Crown/>} title="Subscriptions" text="$5/month Pro plan, family profiles, premium reports."/></section><section className="studio"><div className="panel"><h2>Scan studio</h2><div className="tabs">{['food','medicine','cosmetic','supplement'].map(x=><button className={type===x?'active':''} onClick={()=>{setType(x);setText(samples[x])}}>{x}</button>)}</div><textarea value={text} onChange={e=>setText(e.target.value)}/><input placeholder="Allergies: lactose, peanut" value={allergy} onChange={e=>setAllergy(e.target.value)}/><input placeholder="Medications: warfarin, aspirin" value={meds} onChange={e=>setMeds(e.target.value)}/><button onClick={analyze}>Generate report</button></div><div className="panel"><h2>Truth report</h2>{report?<><div className="score">{report.score}</div><p>{report.high} serious alerts • {report.med} caution flags • {report.good} good signals</p>{report.f.map((x,i)=><div className={'alert '+x.risk} key={i}><b>{x.name}</b><small>{x.desc}</small></div>)}<h3>Better alternatives</h3><div className="alert alt"><b>Cleaner {type} option</b><small>Production version connects to product databases and nearby stores.</small></div></>:<p>Run a scan to generate a report.</p>}</div></section><section className="grid"><Card icon={<User/>} title="Auth" text="Ready for Supabase user accounts and profiles."/><Card icon={<Database/>} title="Database" text="Products, ingredients, scans, alternatives and users."/><Card icon={<Activity/>} title="Admin" text="Metrics, high-risk flags, growth and conversion."/><Card icon={<Crown/>} title="Stripe" text="Premium subscription architecture included."/></section><footer>TruthLabel V1 startup architecture. Not medical advice.</footer></main>}
function Card({icon,title,text}){return <div className="card">{icon}<h3>{title}</h3><p>{text}</p></div>}
